import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";
import LenisScroller from "./components/lenixScroller";
const ivyPresto = localFont({
  src: "./fonts/ivy-presto-headline.otf",
  variable: "--ivy-presto-headline",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ivyPresto.variable} ${geistMono.variable} font-sans`}
      >
        <LenisScroller>
        <div className="">

        <NavBar/>
        {children}</div></LenisScroller>
      </body>
    </html>
  );
}
